name: Build DEB

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          brew install ldid xz make
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/releases/download/2023-09-26/iPhoneOS16.5.sdk.tar.xz
          tar -xf iPhoneOS16.5.sdk.tar.xz -C $HOME/theos/sdks/

      - name: Build
        run: |
          export THEOS=$HOME/theos
          export PATH=$HOME/theos/bin:$PATH
          gmake package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: FaceIDFor6s.deb
          path: packages/*.deb
